#!/bin/bash
# for my amd64  and i386 desktop
# post install: installed after the base system and after init-my-linux has

# files are stored in /mnt/debhome/xconfig - themes.tar.xz, icons.tar.xz, backgrounds.tar config.tar.xz
# the link /mnt/debhome -> to root directory
# to install themes
if test -f /mnt/debhome/xconfig/themes.tar.xz; then
	# extract to /usr/share if they do not exist
	tar --xz -xvf /mnt/debhome/xconfig/themes.tar.xz -C /usr/share/
fi
# extract all icons if Tela-circle-dark does not exist
if test -f /mnt/debhome/xconfig/icons.tar.xz; then
	tar --xz -xvf /mnt/debhome/xconfig/icons.tar.xz -C /usr/share/
fi

# extract dconf and mate for config
# -> .config
if test -f /mnt/debhome/xconfig/config.tar.xz; then
	tar --xz -xvf /mnt/debhome/xconfig/config.tar.xz -C /home/robert
fi

#extract backgrounds to /home/robert/.local/share/backgrounds
if test -f /mnt/debhome/xconfig/backgrounds.tar; then
	tar -xvf /mnt/debhome/xconfig/backgrounds.tar -C /usr/share
fi
