#!/bin/bash
# for my amd64  and i386 desktop
# post install: installed after the base system and after init-my-linux has

# files are stored in /mnt/debhome/xconfig - themes.tar.xz, icons.tar.xz, backgrounds.tar config.tar.xz
# the link /mnt/debhome -> to root directory
# to install themes
if test -f /mnt/debhome/xconfig/themes.tar.xz; then
	# Only Yaru- themes here
	tar --xz -xvf /mnt/debhome/xconfig/themes.tar.xz -C /usr/share/
fi
# extract all Yaru- icons to /usr/share/icons
if test -f /mnt/debhome/xconfig/icons.tar.xz; then
	tar --xz -xvf /mnt/debhome/xconfig/icons.tar.xz -C /usr/share/
fi

# extract dconf and mate for config
# -> .config
if test -f /mnt/debhome/xconfig/config.tar.xz; then
	tar --xz -xvf /mnt/debhome/xconfig/config.tar.xz -C /home/robert
fi

#extract backgrounds to /usr/share/backgrounds
if test -f /mnt/debhome/xconfig/backgrounds.tar; then
	tar -xvf /mnt/debhome/xconfig/backgrounds.tar -C /usr/share
fi

# extract cascadia fonts to /usr/share/fonts
if test -f /mnt/debhome/xconfig/fonts.tar.xz; then
	tar -xvf /mnt/debhome/xconfig/font.tar.xz -C /usr/share
